name: Bug
description: Report a bug or issue
title: ":boom: "
# labels: ["issue-type: bug", "issue-status: triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a **bug** issue! Please fill out the sections below to help us understand your request.
        
        Please note that issues are reserved for feature requests and bug reports. If you have a question or need help, please visit the [GitHub Discussions](about:blank).
  - type: input
    id: part
    attributes:
      label: Part of the project
      description: What part of the project where the bug occurred?
      placeholder: Enter the part of the project where the bug occurred.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug or issue.
      placeholder: Enter a description of the bug or issue. Please be as clear and concise as possible.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the bug.
      placeholder: Go to '...', click on '...', scroll down to '...', see error.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: Enter a description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots etc. here.
      placeholder: Enter any additional context, screenshots etc.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](about:blank).
      options:
        - label: I agree to the Code of Conduct
          required: true
