name: Feature
description: Suggest an idea for a new feature or enhancement
title: ":star2: "
# labels: ["issue-type: feature", "issue-status: triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a **feature** issue! Please fill out the sections below to help us understand your request.
        
        Please note that issues are reserved for feature requests and bug reports. If you have a question or need help, please visit the [GitHub Discussions](about:blank).
  - type: input
    id: part
    attributes:
      label: Part of the project
      description: What part of the project does this feature relate to?
      placeholder: Enter the part of the project that this feature relates to.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature request.
      placeholder: Enter a description of the feature request. Please be as clear and concise as possible.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Are there any alternative solutions or features you've considered?
      placeholder: Enter any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, implementation ideas etc. here.
      placeholder: Enter any additional context, screenshots, implementation ideas etc.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](about:blank).
      options:
        - label: I agree to the Code of Conduct
          required: true
